rootProject.name = "simplecloud"
include("api")
include("api-impl")
include("api-internal")
include("event-api")
include("ignite")
include("application-loader")
include("module-loader")
include("kubernetes")
include("rest-server")
include("node")
include("plugin")
include("content-server")
