apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: microk8s-hostpath
---
apiVersion: v1
kind: Pod
metadata:
  name: mc-server
  labels:
    app: mc-server
spec:
  containers:
    - image: localhost:32000/paper-1.18:latest
      name: simplecloud-process
      ports:
        - containerPort: 25565
      env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "PAPER"
      resources:
        requests:
          memory: 1024Mi
        #limits:
        #  memory: 1024Mi
      volumeMounts:
        - mountPath: /data
          name: cloud-volume
  volumes:
    - name: cloud-volume
      persistentVolumeClaim:
        claimName: claim-server
---
apiVersion: v1
kind: Service
metadata:
  name: mc-service
spec:
  type: NodePort
  selector:
    app: mc-server
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 30009