apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: content-server-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: content-server
  labels:
    simplecloud: content-server
spec:
  containers:
    - name: content-server
      image: 10.43.3.168:5000/simplecloud3-content-server:latest
      volumeMounts:
        - name: cloud-volume
          mountPath: "/app/files/usr"
      ports:
        - containerPort: 8008
  volumes:
    - name: cloud-volume
      persistentVolumeClaim:
        claimName: content-server-claim
---
apiVersion: v1
kind: Service
metadata:
  name: content
spec:
  selector:
    simplecloud: content-server
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008