apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: simplecloud-binding
subjects:
  - kind: ServiceAccount
    name: simplecloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: simplecloud-role
