apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: simplecloud-role
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - exec
    apiGroups:
      - ''
    resources:
      - pods
      - pods/log
      - pods/status
      - services
      - secrets
      - configmaps
      - persistentvolumes
      - persistentvolumeclaims
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - patch
    apiGroups:
      - apps
    resources:
      - deployments